version: '3'

services:
  app:
    build: .
    container_name: casos-clinicos-review
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  reset-data:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: >
      sh -c "rm -rf /data/correcciones/* /data/correctas/* /data/incompletos/* /data/pendientes/* && 
            cp /data/reg/*.json /data/pendientes/"