version: '3'

services:
  app:
    build: .
    container_name: casos-clinicos-review
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - GIT_REPO=Ainovis/revisadorCasosClinicos
    
  reset-data:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: >
      sh -c "rm -rf /data/correcciones/* /data/correctas/* /data/incompletos/* /data/pendientes/* && 
            cp /data/reg/*.json /data/pendientes/"
            
  branch-info:
    build: .
    volumes:
      - ./data:/app/data
    command: ["sh", "-c", "cat /app/data/.branch_name || echo 'No branch name found'"]